#!/bin/bash

set -e

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. /opt/openfoam-dev/etc/bashrc

# Run the meshing and preparations
runApplication surfaceFeatures -dict ./system/surfaceFeatureExtractDict   
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet

# Run the solver
runApplication porousSimpleFoam | tee log logs/log_$(date '+%y-%m-%d_%X')


# Alternative to solver, adjust according to server
# decomposePar
# mpirun -np 4 pimpleFoam -parallel > log.pimpleFoam &
# reconstructPar



# Notes
#cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication blockMesh -dict $FOAM_TUTORIALS/resources/blockMesh/angledDuct
#runApplication $(getApplication)

